version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis  # Adicionando dependência do Redis
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/appdb  # Atualizando para appdb
      # Other environment variables are loaded from .env file
    env_file:
      - .env

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin_restaurante
      - POSTGRES_PASSWORD=senha_super_secreta
      - POSTGRES_DB=restaurante_db  # Atualizando para restaurante_db
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
